### ISSUE TITLE
No syntax highlighting, and errors like "Connection got disposed"

### ISSUE THREAD

**Issue by majelbstoat** [tilt-dev/vscode-tilt#38]
I have a Tiltfile in my repo, and vscode-tilt installed. The extension itself is activated, because I can see the link to the Tilt UI in the status bar. However, the Tiltfile is not syntax highlighted. The language mode is listed as Plain Text and there is no option to set a file association of Tilt/Tiltfile/starlark.

Possibly related: this shows under output:

```
[Info  - 8:36:56 AM] Tiltfile LSP started
[Info  - 8:36:56 AM] Restarting server
[Info  - 8:36:56 AM] Found Tilt version 0.33.10
[Info  - 8:36:56 AM] Starting child process
Starlark LSP server initialized
[Error - 8:36:57 AM] Server initialization failed.
Error: Connection got disposed.
    at Object.dispose (/Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:29:4041)
    at Object.dispose (/Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:34:9518)
    at /Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:36:6952
[Error - 8:36:57 AM] Starting client failed
Error: Connection got disposed.
    at Object.dispose (/Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:29:4041)
    at Object.dispose (/Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:34:9518)
    at /Users/me/.vscode/extensions/tilt-dev.tiltfile-0.0.3/out/extension.js:36:6952
[Info  - 8:36:57 AM] Tiltfile LSP started
[Info  - 8:36:57 AM] Found Tilt version 0.33.10
[Info  - 8:36:57 AM] Starting child process
Starlark LSP server initialized
```

**Comment by majelbstoat** [comment]
After installing and reinstalling twice, and reloading the extension twice, I finally got it to work. Might be a transient error. Feel free to close if the above error is somewhat expected :)
